### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ryo-funaba** [textlint-rule/textlint-rule-rousseau#8]
This is the same issue as https://github.com/textlint-rule/textlint-rule-rousseau/issues/6

【issue】
While using this repository, I received **a critical security notice** from Dependabot regarding prototype pollution in lodash.

The security notice is [here](https://github.com/ryo-funaba/ryo-funaba/security/dependabot/3).

```
Versions of lodash before 4.17.12 are vulnerable to Prototype Pollution. 
The function defaultsDeep allows a malicious user to modify the prototype of Object via {constructor: {prototype: {...}}} causing the addition or modification of an existing property that will exist on all objects.
```

【solution】
I think updating lodash version to 4.17.12 or higher will solve this issue.

Thank you.

**Comment by azu** [comment]
https://github.com/GitbookIO/rousseau/blob/e7fb314d53074f65449d8e5c02a0dd7c932b83ae/package.json#L8-L15
This looks like rousseau issue.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/19714/189465361-404d33b6-e636-43e7-984f-bf152999233f.png">

**Comment by azu** [comment]
Probably, [rousseau](https://github.com/GitbookIO/rousseau) is not maintenanced.
It may be appropriate to fork rousseau as `@textlint-rule/rousseau`

**Comment by ryo-funaba** [comment]
>Edit: I've forked https://github.com/textlint-rule/rousseau

Thank you for your prompt support 🚀 

Would you be willing to update packages in textlint-rule/rousseau?

**Comment by azu** [comment]
https://github.com/textlint-rule/rousseau/issues/3
https://github.com/textlint-rule/rousseau/issues/1

Sub dependencies also need to be updated.

**Comment by azu** [comment]
I've created @textlint-rule/rousseau.

- https://github.com/textlint-rule/rousseau

Welcome PR into this rule.

**Comment by ryo-funaba** [comment]
Thank you for creating @textlint-rule/rousseau.

I will create a PR that solves this problem!
